### ISSUE TITLE
Adding New Blueprints

### ISSUE THREAD

**Issue by BurlyWurly** [OwlcatOpenSource/WrathModificationTemplate#16]
So last I'd heard no one had successfully created/added new blueprints using these tools. Is that still the case or has anyone managed to crack this one yet?

**Comment by Xehanort88** [comment]
Thats because the tools are woefully inadequate I fear.

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il Sab 16 Ott 2021, 4:11 PM BurlyWurly ***@***.***> ha
scritto:

**Comment by BurlyWurly** [comment]
Not really, no, it's more that there's virtually no directions on how to use them. They've proven effective and easy to actually use for the bulk of what I've been trying to do with them. The catch is that the directions don't include the vast majority of the inputs you actually need to do most things. 

ijuintekka seems to have managed to uncover alot of these syntaxes/formats that I had assumed were just impossible to know without a developer response, so this is mainly aimed at them. Or the actual devs should they monitor their own page, god forbid.

**Comment by ijuintekka** [comment]
Not every type requires a GUID in the blueprint, this is something that's added in the dumping process. If you recall, in your previous issue, I told you that a type had no guid and that the line was safe to erase; This is true of every type without a guid, and all three DamageTypeDescription types fall into this category. The blueprint interpreter already knows it's expecting these. As a general rule you also don't need the "$id": tags either, it's safe to get rid of them, they only cause issues if you accidentally duplicate them.

**Comment by BurlyWurly** [comment]
Yeah I tried a workaround like that, which meant PaladinsRingItem now had two enchantments, and each enchantment pointed to a separate feature, one which increased one resource and the other which increased the other. Still only one applied in game. Especially since that seems to be what you're doing that really should work...I guess I'll try and iterate on that method a bit more and see if I can make it work.

It's definitely patching. But once I get in game and go through character selection, the original deity is definitely gone, but the new one isn't there. There's deities that are like this too even when you run the game vanilla- Green Faith for example is in DeitySelection but doesn't appear as an option when you try creating a character. I recreated the original deity blueprint line for line, except for adding an additional blueprint in the list of selectable domain blueprints, so I don't think it's within the deity blueprint.

**Comment by BurlyWurly** [comment]
Only thing remotely similar is the 'NoArchetype' prereq. Like I said it's a line by line recreation of Shelyn who is generally selectable.

**Comment by ijuintekka** [comment]
The problem is your description keys not being correctly formatted. They should look like this:

        "m_DisplayName": {
            "m_Key": "DisplayKey"
        },
        "m_Description": {
            "m_Key": "DescriptionKey"
        },
        "m_DescriptionShort": {
            "m_Key": "ShortKey"
        },

**Comment by BurlyWurly** [comment]
Yep that did the trick...dunno why I messed that up, it looks like I remembered to do it on other blueprints.

What seems to be getting me now is...once again Components. It's not showing any Domains or Channel Energy options as selectable, which is obviously the AddFacts component. Though if the whole Components section were broken I don't know how I'd tell tbh. This seems extremely straightforward so I'm not sure what could be going wrong here.

**Comment by ijuintekka** [comment]
You have a stray comma at the end of AddFeatureOnClassLevel.

 "m_Archetypes": [],
"Level": 1, <---- Here
},

**Comment by ijuintekka** [comment]
And PrerequisiteAlignment, AddStartingEquipment, and both PrerequisiteNoArchetypes.

**Comment by ijuintekka** [comment]
Every line has to be indented with at least 4 spaces.

**Comment by BurlyWurly** [comment]
Huh, well that explains a lot. Thank you so much for the help! Man the unwritten rules on this thing can really get ya.

**Comment by ijuintekka** [comment]
The readme is fairly comprehensive for localization, but I'll break it down as simply as I can. Just as a tip; you don't actually need a guid for description keys, it will accept any input so you can use a friendly name to make things easier if you want.

Your mod should have a "Localization" subfolder, create one if it doesn't, and in this sub folder create an empty text file named enGB.json, put your keys in here formatted like my example:
```
{
    "strings": [{
            "Key": "LissalaFeature_DisplayName",
            "Value": "Lissala"
        }, {
            "Key": "LissalaFeature_Description",
            "Value": "Lissala, also known as \"The Scion of Seven\" and \"The Order of Virtue\", is the goddess of runes, fate, and the reward of service, and was once a major religious force in the empires of Azlant and Thassilon. Lissala teaches the philosophical concept of the \"Seven Virtues of Rule\" and she finds worshipers among those who dedicate their life and work to law and the revelation of knowledge.\nDomains: Evil, Knowledge, Law, Nobility, Rune.\nFavored Weapon: Whip (Flail)"
        }, {
            "Key": "LissalaFeature_DescriptionShort",
            "Value": "Lissala is the goddess of runes, fate, and the reward of service."
        }
    ]
}
```
Then you reference it in your blueprint as normal:
```
        "m_DisplayName": {
            "m_Key": "LissalaFeature_DisplayName"
        },
        "m_Description": {
            "m_Key": "LissalaFeature_Description"
        },
        "m_DescriptionShort": {
            "m_Key": "LissalaFeature_DescriptionShort"
        },
```
Then build your mod and you're done.

**Comment by hmmvot** [comment]
Could someone summarize the problem if it's still exists?

**Comment by ijuintekka** [comment]
I think this has been resolved.
