### ISSUE TITLE
Patching Blueprints After 1.1.1

### ISSUE THREAD

**Issue by BurlyWurly** [OwlcatOpenSource/WrathModificationTemplate#18]
So, I noticed the update to the instructions regarding blueprint patches and had a couple of questions.

1. Will blueprint patches as written cease working with 1.1.1 unless modified?
2. Assuming yes to 1, do we just need to add `"_#ArrayMergeSettings": "Merge",` at the beginning and that new Component with m_Flag: 1 to make them work again?
3. Since I see this new patch format includes a component alteration in it, does that mean component patching will work in 1.1.1?

**Comment by hmmvot** [comment]
1-2. Old-style patches will work without modification. Default value of `"_#ArrayMergeSettings"` is `"Replace"`.
3. Yes, 1.1.1 supports modification of component's fields.

**Comment by hmmvot** [comment]
I'll update `Example Modification` for the new patch format after release of 1.1.1

**Comment by BurlyWurly** [comment]
Awesome, thank you for the clarification!
