### ISSUE TITLE
LocalizedName

### ISSUE THREAD

**Issue by FrozenDervish** [OwlcatOpenSource/WrathModificationTemplate#19]
I'm having issues in how to make this work. I've tried just about everything I can think of to make it work.

"LocalizedName": null,

Is what I am talking about. What is used to replace the null value?

**Comment by BurlyWurly** [comment]
Are you trying to put something new there, or just translate into an input syntax? If you're trying to have a new LocalizedName, you need to add a string to your localization patch and reference the key. If you're just trying to figure out how to input "LocalizedName": null correctly, empty quotations mark are the input for null i.e.:
`"LocalizedName": ""`

**Comment by FrozenDervish** [comment]
Ya, that's exactly what I'm looking for. The issue stems from when I do that to add an Archetype the entire Archetype list disappears in the game, and I'm not sure what causes it except for the LocalizedName causing an issue.

**Comment by BurlyWurly** [comment]
I've seen an option not appearing on the selection list when it was broken but never the whole selection list disappearing. Doesn't strike me as impossible though. Why don't you link the entire blueprint?

**Comment by FrozenDervish** [comment]
`{
  "AssetId": "6f3e44ec19f53994d943144b32ba35fc",
  "Data": {
    "$type": "f04f17ea4eae4fb89afa5b4021444740, BlueprintArchetype",
    "PrototypeLink": null,
    "m_Overrides": [],
    "Components": null,
    "Comment": null,
    "LocalizedName": "TestName00001,
    "LocalizedDescription": null,
    "LocalizedDescriptionShort": null,
    "m_Icon": null,
    "m_ReplaceSpellbook": "!_bp682545e11e5306c45b14ca78bcbe3e62",
    "RemoveSpellbook": false,
    "BuildChanging": false,
    "AddFeatures": [{
		
                "m_Features": ["!bp_5b31af13868166d4c9bb452f19277f19"],
				"Level": 20
            },
			
			
			
			],
    "RemoveFeatures": [{
		
                "m_Features": ["!bp_789c7539ba659174db702e18d7c2d330"],
				"Level": 20
            },
			
			
			],
    "ReplaceStartingEquipment": false,
    "StartingGold": 0,
    "m_StartingItems": [],
    "ReplaceClassSkills": false,
    "ClassSkills": [],
    "ChangeCasterType": false,
    "IsDivineCaster": false,
    "IsArcaneCaster": false,
    "AddSkillPoints": 0,
    "OverrideAttributeRecommendations": false,
    "RecommendedAttributes": [],
    "NotRecommendedAttributes": [],
    "m_SignatureAbilities": [],
    "m_BaseAttackBonus": null,
    "m_FortitudeSave": null,
    "m_ReflexSave": null,
    "m_WillSave": null,
    "m_Difficulty": 1
  }
}`

It's odd cause when the name is null it works just fine with the exception of being null.

**Comment by ijuintekka** [comment]
Text fields don't accept a straight string. In the case of a Localized string you need to format it thusly:

"LocalizedName": { "Shared": { "stringkey": "YourStringKeyHere" } }

**Comment by BurlyWurly** [comment]
I don't have any archetypes but here's one of my Background blueprints, principles are the same:
```
{
  "AssetId": "5c5cd2e477739b54db7c363b6373c4a6",
  "Data": {
     "$type": "cb208b98ceacca84baee15dba53b1979, BlueprintFeature",
     "Groups": [],
     "Ranks": 1,
     "IsClassFeature": true,
     "IsPrerequisiteFor": [],
     "PrototypeLink": "",
     "m_Overrides": [],
     "Components": [
       {
         "$type": "7a5d4700264de3b4aacf2514df964a14, AddClassSkill",
         "Skill": "SkillPersuasion",
         "name": "unique_reference_a"
       },
       {
         "$type": "2286a148d6ca486091b6f0d687d6486f, AddBackgroundClassSkill",
         "Skill": "SkillPersuasion",
         "name": "unique_reference_b"
       },
       {
         "$type": "df930d377a444922b2267e07a7d40b93, AddBackgroundWeaponProficiency",
         "Proficiency": "Longspear",
         "StackBonusType": "Trait",
         "StackBonus": {
           "m_CustomProperty": "",
           "Value": 1
         },
         "name": "unique_reference_c"
       },
       {
         "$type": "df930d377a444922b2267e07a7d40b93, AddBackgroundWeaponProficiency",
         "Proficiency": "Greatsword",
         "StackBonusType": "Trait",
         "StackBonus": {
           "m_CustomProperty": "",
           "Value": 1
         },
         "name": "unique_reference_d"
       },
       {
         "$type": "ae4b8f851e894c3faa63ceae8ac01cbc, AddBackgroundArmorProficiency",
         "Proficiency": "Medium",
         "StackBonus": {
           "m_CustomProperty": "",
           "Value": 1
         },
         "name": "unique_reference_e"
       },
       {
         "$type": "ae4b8f851e894c3faa63ceae8ac01cbc, AddBackgroundArmorProficiency",
         "Proficiency": "Heavy",
         "StackBonus": {
           "m_CustomProperty": "",
           "Value": 1
         },
         "name": "unique_reference_f"
       },
       {
         "$type": "f91f722f0f3382a43a23733b68cdfba4, ArmorFocus",
         "ArmorCategory": "Heavy",
         "name": "unique_reference_x"
       },
       {
         "$type": "d79ad4ed064aa4f43ace0e9c238fb9b9, AddFacts",
         "m_Facts": [
           "!bp_9c7b33404dc0ac1449ee2732657b722a",
           "!bp_f35e15b1fdff0c54087746c2da80a053"
         ],
         "name": "unique_reference_g"
       }
    ],
    "m_DisplayName": {"m_Key": "KnightFeature_DisplayName"},
    "m_Description": {"m_Key": "KnightFeature_Description"},
    "m_DescriptionShort": {"m_Key": ""},
    "m_Icon": {"guid": "3ec5e563b1a087d4992630027c74afb5", "fileid": 21300000}  
  }
}
```
So ijuintekka can correct me if I'm wrong here, but you have to replace all those null references with empty quotations as you'll see I have throughout mine. Even if your archetype is selectable, that doesn't mean it isn't broken. A common symptom I've found with a broken but selectable character option is you can't save your game if you have a character with that option selected.

There's instructions here on the github about localization that are pretty good. You have to reference the key in your blueprint. You actually write out the string in the localization file 'enGB'.

You've also broken the spellbook with a typo '!_bp<guid>' vs '!bp_<guid>'

**Comment by ijuintekka** [comment]
null or "" will work interchangeably in many cases, except with fields that explicitly don't allow null.

**Comment by FrozenDervish** [comment]
> 
> 
> Text fields don't accept a straight string. In the case of a Localized string you need to format it thusly:
> 
> "LocalizedName": { "Shared": { "stringkey": "YourStringKeyHere" } }

Brilliant! That worked, thank you!

If I may ask how did you find that?

**Comment by ijuintekka** [comment]
At the time I made an archetype, during the beta, using m_Key wasn't working for me and some of the old patches used Shared:stringkey instead. I've actually gone back and checked just now and m_Key is working fine!

So I guess you can use "LocalizedName": { "m_Key": "YourKeyHere" } to keep things neater.

**Comment by FrozenDervish** [comment]
Another question.

When creating a new class blueprint is there a selection blueprint to go with it? If there is I can't find it and simply making a new class blueprint doesn't add it to the Choose Class list.

**Comment by ijuintekka** [comment]
It's in BlueprintRoot, m_CharacterClasses array.

**Comment by FrozenDervish** [comment]
> 
> 
> It's in BlueprintRoot, m_CharacterClasses array.

You're awesome! 

And do you know if Union/Concat/Replace works for merging?

**Comment by ijuintekka** [comment]
Union and Concat should in theory work in a similar manner to Merge, just with slightly different methods of getting there. Union should strip out any duplicates for example. Of course we'll have to wait for the next patch to find out.

Resource syntax is:

"resourcename": { "AssetId": "guid" }
