### ISSUE TITLE
Some blueprint patches no longer patching 1.1.1

### ISSUE THREAD

**Issue by BurlyWurly** [OwlcatOpenSource/WrathModificationTemplate#21]
So I fired up the game as soon as the patch hit, and I'm finding a confusing mix of issues now. 

My mod that patches all the different iterations of Radiance to change its weapon type continues to work without issue.

My backgrounds mod is no longer patching the selection. The new backgrounds still show up on saved games on characters that had selected them. 

My general item mod that patches a bunch of different items doesn't appear to be applying any of the patches anymore. The mod itself is getting applied - localization changes all still show up.

Posting a couple example patches. All of these worked a few hours ago.

Doesn't work:
```
{
  m_Type: "!bp_afd9065539b3ac5499eddca923654c4b",
  m_Enchantments: [
    "!bp_a9ea95c5e02f9b7468447bc1010fe152",
    "!bp_32ada6d4c9592f840a99ec72354cb006",
    "!bp_7b95a819181574a4799d93939aa99aff"
  ],
  m_EquipmentEntity: "!bp_4c66bd5edb27a9b48be95e78eabd4bea",
  m_Icon: {"guid": "a424f998ed2d79d429523a986d8bfc9c", "fileid": 21300000},
  m_Cost: 22850,
  m_Weight: 25.0
}
```

Works:
```
{
m_Type: "!bp_5f824fbb0766a3543bbd6ae50248688f",
m_Enchantments: ["!bp_d42fc23b92c640846ac137dc26e000d4", "!bp_e5990dc76d2a613409916071c898eee8", "!bp_20ba9055c6ae1e44ca270c03feacc53b"],
m_VisualParameters: {
    "m_Projectiles": [],
    "m_WeaponModel": {"AssetId": "e72d2905c99434a4e815e25445d62b81"},
    "m_WeaponBeltModelOverride": {"AssetId": ""},
    "m_WeaponSheathModelOverride": {"AssetId": "a0ebe3bd23628c04c90559afbf9fb3c7"},
    "m_PossibleAttachSlots": [],
    "m_WhooshSound": "",
    "m_EquipSound": "",
    "m_UnequipSound": "",
    "m_InventoryEquipSound": "",
    "m_InventoryPutSound": "",
    "m_InventoryTakeSound": ""
  },
m_Icon: {"guid": "e99751bdc54aec042b0c68d33ed73b39", "fileid": 21300000}
}
```

Doesn't work:
```
{
"m_Features": [
    "!bp_20345da9d16f71f4184e77fd2f81701f",
    "!bp_f723632a2ed8e5840ab4ec82bb30c796",
    "!bp_e640977fca3b7f04d9257c9648c027de",
    "!bp_5c5cd2e477739b54db7c363b6373c4a6"
  ],
  "m_AllFeatures": [
    "!bp_20345da9d16f71f4184e77fd2f81701f",
    "!bp_f723632a2ed8e5840ab4ec82bb30c796",
    "!bp_e640977fca3b7f04d9257c9648c027de",
    "!bp_5c5cd2e477739b54db7c363b6373c4a6"
  ]
}
```

Any idea what's up? Does this have something to do with the merging change that was made? The weirdest part is just how some work and some don't, it'd make a lot more sense if it was all or nothing.

**Comment by hmmvot** [comment]
Is any error appears in log? You can use external [console](https://github.com/OwlcatOpenSource/RemoteConsole/releases/tag/v1.0.0) and filter messages by Mods channel.

**Comment by BurlyWurly** [comment]
![image](https://user-images.githubusercontent.com/91348172/140901316-fc39b400-1e22-4e24-b472-7b62755732b1.png)

Doesn't look to be any error messages with the mods from what I can tell, but this is also my first time using that console.

**Comment by BurlyWurly** [comment]
The fact that GreatRadiance was loading last is definitely relevant. When I load the BetterBackgrounds mod by itself, it's patches all work.

Again, before patch 1.1.1 there was no issue running multiple mods that had blueprint patches.

**Comment by ijuintekka** [comment]
Sorry to butt in, I'm sorry I don't have anything to add to the discussion of the issue, other than saying all my stuff is still working fine. I just wanted to thank you @hmmvot and the rest of the team for getting this update out and including the blueprints archive. It's such a boon for modding to have everything correctly formatted. Great stuff!

**Comment by hmmvot** [comment]
> The fact that GreatRadiance was loading last is definitely relevant. When I load the BetterBackgrounds mod by itself, it's patches all work.
> 
> Again, before patch 1.1.1 there was no issue running multiple mods that had blueprint patches.

Did you rebuild your modification with new assemblies from the game? Please attach your modification if you did and it didn't help.

**Comment by BurlyWurly** [comment]
[GreatRadiance.zip](https://github.com/OwlcatOpenSource/WrathModificationTemplate/files/7505799/GreatRadiance.zip)
[BetterBackgrounds.zip](https://github.com/OwlcatOpenSource/WrathModificationTemplate/files/7505805/BetterBackgrounds.zip)
[BurlyItems.zip](https://github.com/OwlcatOpenSource/WrathModificationTemplate/files/7505806/BurlyItems.zip)

Mods are attached. They've all been rebuilt as part of troubleshooting.

**Comment by ijuintekka** [comment]
Can confirm. I added more mods and all my patches stopped working.

**Comment by ijuintekka** [comment]
Seems that every time a new mod from the list is loaded all the previous patches are undone so only the final mod's patches remain.

**Comment by FrozenDervish** [comment]
> 
> 
> Sorry to butt in, I'm sorry I don't have anything to add to the discussion of the issue, other than saying all my stuff is still working fine. I just wanted to thank you @hmmvot and the rest of the team for getting this update out and including the blueprints archive. It's such a boon for modding to have everything correctly formatted. Great stuff!

Where do we find this archive?

**Comment by ijuintekka** [comment]
Once you're on patch 1.1.1, check the root directory of your installation for blueprints.zip

**Comment by FrozenDervish** [comment]
> 
> 
> Once you're on patch 1.1.1, check the root directory of your installation for blueprints.zip

Very nice! Thank you once again.

**Comment by BurlyWurly** [comment]
@hmmvot 
Is there any update on whats causing this? Is there something we can do about it or is it going to require a hotfix?

**Comment by hmmvot** [comment]
Hotfix required for fixing this issue. The problem appears only if you load two or more mods (only patches from lastly loaded mod will be applied).

**Comment by BurlyWurly** [comment]
Gotcha, thanks for the confirmation. Any idea when we can expect that to be deployed?

**Comment by hmmvot** [comment]
> Gotcha, thanks for the confirmation. Any idea when we can expect that to be deployed?

Today or tomorrow.

**Comment by BurlyWurly** [comment]
The patch appears to have done its work well. My mods are all friends again. Great work and thank you so much!
