### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by WittleWolfie** [OwlcatOpenSource/WrathModificationTemplate#3]
Without an explicit license, the WrathModificationTemplate maintains exclusive copyright. This technically prevents mod developers from using this template to create and publish modifications: [Github - No License](https://choosealicense.com/no-permission/).

While I'm sure Owlcat has no intentions to prosecute mod developers, a licensing file ensures protection for mod developers and makes your policy on modifying and publishing the template clear.

**Comment by TylerGoeringer** [comment]
Any update here? Some devs have been hesitant to onboard to this and pretty much all devs using this are keeping their source private until licensing is clear. I know you are all working hard on patching bugs but this feels like it should be straightforward to address--your other projects have licenses already.

**Comment by Xehanort88** [comment]
Yeah that's largely incomprehensible for me. Tools should be at least
semi-accessible.

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il Sab 18 Set 2021, 8:23 PM Tyler Goeringer ***@***.***> ha
scritto:
