### ISSUE TITLE
Error setting value to 'm_Icon' on 'Kingmaker.Blueprints.Classes.BlueprintFeature'

### ISSUE THREAD

**Issue by TylerGoeringer** [OwlcatOpenSource/WrathModificationTemplate#4]
Repro Steps:

1. Create a new mod under Assets/Modifications, e.g. WrathModificationTemplate/Assets/Modifications/MyMod
2. Follow steps in Readme to get mod ready to build
3. Create a BlueprintFeature 
4. Import an icon: Right Click in MyMod/Content > Import New Asset > Select *.png file (importing TestIcon.png from the Example is fine)
5. Select the asset and ensure the 'Texture Type' is 'Sprite (2D and UI)'
6. Right Click the asset > Modification Tools > Copy GUID and File ID
7. Paste the GUID and File ID into the m_Icon field of your blueprint
8. Build and install the mod
9. Launch WotR

In AppData the game log will show an error when loading the blueprint:

`
Error setting value to 'm_Icon' on 'Kingmaker.Blueprints.Classes.BlueprintFeature'
...
Inner: Object of type 'UnityEngine.Texture2D' cannot be converted to type 'UnityEngine.Sprite'.
`

**Comment by TylerGoeringer** [comment]
An odd one since it works in the example mod but breaks in other folders. I haven't been able to identify what's going on exactly, but I was able to workaround it by changing ExtractBlueprintDirectReferences#LoadAsset() to return only the matching Sprite asset:

`return AssetDatabase.LoadAssetAtPath<Sprite>(path);`

I'm not sure if this is a good fix though since this ignores the fileId entirely. This came from a post on Unity answers: [Editor Script Selection thinks Sprites are Texture2Ds](https://answers.unity.com/questions/1183548/editor-script-selectiongetfiltered-sprites-not-get.html).

**Comment by ijuintekka** [comment]
In my experience the m_Icon fileid field in the blueprint must always be 21300000 or the asset will fail to load. Otherwise it works fine.
![icon](https://user-images.githubusercontent.com/28776339/131461256-be3e36dc-1c56-42fb-b52d-c7c3ca598fd2.png)

**Comment by TylerGoeringer** [comment]
Wow, that does work.

**Comment by TylerGoeringer** [comment]
Update: After more testing, it's loading the blueprint just fine but the icon is just null. Are you building inside of example modification's assembly?

**Comment by hmmvot** [comment]
You should copy guid and file ID for inner asset (like on screenshot) then file ID will be equals to 21300000 
![image](https://user-images.githubusercontent.com/1746645/132736507-b2587883-23fd-494f-9c0b-2eb8324c6e07.png)
