### ISSUE TITLE
Criticism of the patch format.

### ISSUE THREAD

**Issue by ijuintekka** [OwlcatOpenSource/WrathModificationTemplate#6]
The way patches currently behave, by replacing an entire array, will hamper interoperability between modifications. For example, two mods that wish to add new class archetypes could not both add fields to a class blueprint's m_Archetype array via a patch, as one of them would always overwrite the other.

If patches behaved more like a standard diff patch, allowing us to add or remove lines to an array by prefixing them with a + or -, and leaving the rest of the array intact, it would greatly increase the ability of similar mods to operate together.

For example:

{
    "m_Archetypes": [
        -"!bp_ac87f40932cfd324c90b441f93857c40" //Remove This Archetype Blueprint
        +"!bp_639b74fd2f48d474e965c596b1649095" //Add This Archetype Blueprint
    ]
}

**Comment by TylerGoeringer** [comment]
Do patches work at all for blueprint array refs? I tried it for adding a feat to the basic feat selection but it didn't seem to have any effect.

**Comment by ijuintekka** [comment]
I've successfully added new deities and archetypes to their relevant selection blueprints using patches so it's definitely working. While I've not added any new feat selections I'd imagine they're no different. Don't forget to add the patch file name and the original blueprint guid to your BlueprintPatches.asset. My InquisitorClass patch looks like this for reference:

{
    "m_Archetypes": [
        "!bp_ac87f40932cfd324c90b441f93857c40",
		"!bp_0e5e91c17f114d358910e0da4ae29b50",
        "!bp_cdaabf4b146c9ba42ab7d05abe3b48c4",
		"!bp_f0000000000000000000000000000004",
		"!bp_46eb929c8b6d7164188eb4d9bcd0a012",
		"!bp_19b4a243d9a4bd34887d03c3dea03ced",
        "!bp_639b74fd2f48d474e965c596b1649095"
    ]
}

**Comment by TylerGoeringer** [comment]
Thanks, got it working. I had a typo on the fieldname.

Definitely this is one of the biggest issues w/ the Patch system. Right now they're filling in data using Populate() instead of Merge(). Merge() would allow appending content to an array though it doesn't allow removing entries afaik.

**Comment by ijuintekka** [comment]
Good to know. :) Have fun playing the game today!

**Comment by ijuintekka** [comment]
As of patch 1.1.1, this issue is no longer valid. Thank you to all on the team who worked to address this problem.
