### ISSUE TITLE
Logging output suppressed in release

### ISSUE THREAD

**Issue by TylerGoeringer** [OwlcatOpenSource/WrathModificationTemplate#7]
The example uses LogChannel but in the release version of the game, LogChannel doesn't actually output anything. I assume there's some way to configure it but I couldn't find anything.

**Comment by MaxSavenkov** [comment]
You can enable logging in the release version by running it with 'logging' argument on the command line (e.g. Wrath.exe logging) or by specifying it in Steam's game launch settings.
